#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
ENV_FILE=".env.local"

# ── Helpers ──────────────────────────────────────────────────

has_key() { [[ -n "$(_existing "$1" || true)" ]]; }

banner "Is This a Scam? — deploy"

# ── Stage 1 ──────────────────────────────────────────────────
stage "Put a ceiling on what this can cost you"

say "About to make this public. Anyone with the link can run a check, and"
say "every check spends a little of your Anthropic credit."
say ""
say "The app already caps one caller at 20 checks per 10 minutes. That is a"
say "brake, not a guarantee — it lives in memory, so it resets when the server"
say "restarts and does not stop someone changing address."
say ""
warn "The only limit that cannot be out-run is a spend cap at Anthropic."
say ""

if confirm "Open the Anthropic billing page to set one?"; then
  open_url "https://console.anthropic.com/settings/limits"
  step "Set a monthly spend limit you would be relaxed about losing."
  step "A few dollars is plenty — each check costs a fraction of a cent."
  step "Turn on the email alert too, so you hear about it early."
  pause "Set it? Press Enter."
else
  SKIPPED+=("Anthropic spend limit — set one before sharing the link widely")
  warn "skipping — please do this before you give the link to anyone"
  pause
fi

# ── Stage 2 ──────────────────────────────────────────────────
stage "Check it builds before anyone sees it"

say "Running the tests, the type checker, and a real production build."
say ""

if ! npm run verify; then
  warn "tests or types failed — fix these before deploying"
  exit 1
fi

if ! npm run build; then
  warn "the production build failed — fix it before deploying"
  exit 1
fi

printf '  %s✓ tests, types and build all pass%s\n' "$GREEN" "$RESET"
pause

# ── Stage 3 ──────────────────────────────────────────────────
stage "Sign in to Vercel"

if ! command -v vercel >/dev/null 2>&1; then
  say "The Vercel command-line tool is not installed yet."
  if confirm "Install it now with npm?"; then
    npm install -g vercel || {
      warn "install failed — try running: npm install -g vercel"
      exit 1
    }
  else
    warn "cannot deploy without it — install with: npm install -g vercel"
    exit 1
  fi
fi

say "Signing you in. A browser window will open — approve it there."
say ""

if vercel whoami >/dev/null 2>&1; then
  printf '  %s✓ already signed in as%s %s\n' "$GREEN" "$RESET" "$(vercel whoami 2>/dev/null)"
else
  vercel login || {
    warn "sign-in did not complete"
    exit 1
  }
fi
pause

# ── Stage 4 ──────────────────────────────────────────────────
stage "Send your keys up, then deploy"

say "Your keys are in .env.local, which is never committed. Vercel needs its"
say "own copy — these commands push them straight from this machine."
say ""

push_key() {
  local name="$1" value
  value="$(_existing "$name" || true)"

  if [[ -z "$value" ]]; then
    note "$name is not set locally — skipping (that half stays off)"
    SKIPPED+=("$name on Vercel (run scripts/setup.sh first, then re-run this)")
    return
  fi

  # Removing first makes this safe to run again after a key is rotated.
  vercel env rm "$name" production --yes >/dev/null 2>&1 || true
  if printf '%s' "$value" | vercel env add "$name" production >/dev/null 2>&1; then
    printf '  %s✓ sent%s %s to Vercel\n' "$GREEN" "$RESET" "$name"
  else
    warn "could not send $name — add it by hand in the Vercel dashboard"
    SKIPPED+=("$name on Vercel (add it in Project → Settings → Environment Variables)")
  fi
}

say "Linking this folder to a Vercel project. Accept the defaults unless you"
say "have a reason not to."
say ""
vercel link || {
  warn "linking failed"
  exit 1
}

# The AGPL's section 13 obliges an app people only reach over a network to offer
# them its source, and the footer link is that offer. Asked here rather than in
# setup.sh because it is a property of the thing being published, not of the
# machine it was built on — and because this is the last point before it becomes
# public with or without it.
say ""
say "Where can people read this app's source? Your repository address, for the"
say "footer link. The AGPL requires the offer, and it is what lets anyone check"
say "the numbers you are publishing. Leave it empty to deploy without it."
say ""
ask NEXT_PUBLIC_SOURCE_URL "Source address (e.g. https://github.com/you/is-this-a-scam):"
if [[ -n "$NEXT_PUBLIC_SOURCE_URL" ]]; then
  write_env NEXT_PUBLIC_SOURCE_URL "$NEXT_PUBLIC_SOURCE_URL"
else
  SKIPPED+=("NEXT_PUBLIC_SOURCE_URL — the footer will name the licence without linking the source")
fi

push_key ANTHROPIC_API_KEY
push_key SAFE_BROWSING_API_KEY
push_key NEXT_PUBLIC_SOURCE_URL

say ""
say "Deploying to production. This takes a minute or two."
say ""
DEPLOY_URL="$(vercel deploy --prod 2>&1 | tee /dev/tty | grep -oE 'https://[a-zA-Z0-9.-]+\.vercel\.app' | tail -1)"

if [[ -z "$DEPLOY_URL" ]]; then
  warn "could not read the deployed address from the output above"
  ask DEPLOY_URL "Paste the address Vercel printed:"
fi

# ── Stage 5 ──────────────────────────────────────────────────
stage "Prove the live site actually works"

if [[ -z "$DEPLOY_URL" ]]; then
  warn "no address to test — check the Vercel dashboard"
else
  say "Sending a known scam to the live site and reading the answer back."
  say ""

  body=$(mktemp)
  code=$(curl -s -o "$body" -w '%{http_code}' -m 60 -X POST "${DEPLOY_URL}/api/check" \
    -H 'content-type: application/json' \
    -d '{"message":"ASB: unusual login detected. Verify at asb-secure.top"}' || printf '000')

  if [[ "$code" == "200" ]] && grep -q '"level":"scam"' "$body"; then
    printf '  %s✓ the live site correctly called it a scam%s\n' "$GREEN" "$RESET"
  else
    warn "the live site answered ${code} — that is not what we expected:"
    note "$(head -c 400 "$body")"
    SKIPPED+=("live check failed — look at the Vercel deployment logs")
  fi
  rm -f "$body"

  # Not written to .env.local: it is not a secret and not configuration, it is
  # just the address to hand to people.
  say ""
  printf '  %sYour app is live at%s %s%s%s\n\n' "$DIM" "$RESET" "$BOLD" "$DEPLOY_URL" "$RESET"
  open_url "$DEPLOY_URL"
fi

finish

say "Two things worth doing now that it is public:"
say ""
note "  · Vercel dashboard → Firewall → add a rate limit on /api/check."
note "    That one is enforced at the edge, so it holds even when the app"
note "    restarts and forgets its own counts."
note "  · Watch spend for the first day or two at console.anthropic.com."
say ""
