#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

# Run from the project root, whichever directory the script was invoked from.
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

# Next.js reads .env.local, and it is already in .gitignore — so a key pasted
# here cannot be committed by accident.
ENV_FILE=".env.local"

# ── Verification helpers  ──────────────────────────────────────────────────
# Every key is proved with a real call before the wizard moves on. A key that is
# merely stored is a key you find out about later, in front of the person you
# built this for.

http_status() { curl -s -o "$1" -w '%{http_code}' -m 25 "${@:2}" 2>/dev/null || printf '000'; }

verify_anthropic() {
  local key="$1" body code
  body=$(mktemp)
  # count_tokens proves the key without generating a single token, so checking
  # it costs nothing at all.
  code=$(http_status "$body" \
    https://api.anthropic.com/v1/messages/count_tokens \
    -H "x-api-key: ${key}" \
    -H "anthropic-version: 2023-06-01" \
    -H "content-type: application/json" \
    -d '{"model":"claude-opus-5","messages":[{"role":"user","content":"hello"}]}')

  case "$code" in
    200) printf '  %s✓ the key works%s — Claude answered\n' "$GREEN" "$RESET"; rm -f "$body"; return 0 ;;
    401) warn "that key was rejected (401) — check you copied all of it" ;;
    404) warn "the key is valid, but this account cannot reach claude-opus-5 (404)" ;;
    000) warn "could not reach api.anthropic.com — check your connection" ;;
    *)   warn "unexpected response ${code} from Anthropic:"; note "$(head -c 300 "$body")" ;;
  esac
  rm -f "$body"
  return 1
}

verify_safe_browsing() {
  local key="$1" body code
  body=$(mktemp)
  # Google publishes this address purely so tools can prove the lookup works. A
  # key that is valid but whose API has not been switched on returns 403 here,
  # which is the mistake worth catching now rather than in production.
  code=$(http_status "$body" -X POST \
    "https://safebrowsing.googleapis.com/v4/threatMatches:find?key=${key}" \
    -H 'content-type: application/json' \
    -d '{"client":{"clientId":"is-this-a-scam","clientVersion":"0.0.1"},"threatInfo":{"threatTypes":["MALWARE","SOCIAL_ENGINEERING"],"platformTypes":["ANY_PLATFORM"],"threatEntryTypes":["URL"],"threatEntries":[{"url":"http://malware.testing.google.test/testing/malware/"}]}}')

  if [[ "$code" == "200" ]]; then
    if grep -q '"matches"' "$body"; then
      printf '  %s✓ the key works%s — it correctly flagged Google'"'"'s test address\n' "$GREEN" "$RESET"
    else
      printf '  %s✓ the key works%s — the API answered cleanly\n' "$GREEN" "$RESET"
      note "it did not flag the test address, which is unusual but not fatal"
    fi
    rm -f "$body"; return 0
  fi

  case "$code" in
    403) warn "403 — the key is valid but the Safe Browsing API is not switched on for it"
         note "go back and click Enable for this project, then try again" ;;
    400) warn "400 — that usually means the key itself is wrong" ;;
    000) warn "could not reach safebrowsing.googleapis.com — check your connection" ;;
    *)   warn "unexpected response ${code} from Google:"; note "$(head -c 300 "$body")" ;;
  esac
  rm -f "$body"
  return 1
}

# capture_key VAR "Prompt" verify_fn — ask, verify, and loop until it works or the
# human gives up. Nothing reaches .env.local until it has been proven.
capture_key() {
  local var="$1" prompt="$2" verifier="$3" value

  while true; do
    ask_secret "$var" "$prompt"
    value="${!var}"

    if [[ -z "$value" ]]; then
      warn "nothing pasted — skipping this one"
      SKIPPED+=("$var (skipped; re-run this script any time to add it)")
      return 1
    fi

    printf '  %s… checking it against the real service%s\n' "$DIM" "$RESET"
    if "$verifier" "$value"; then
      write_env "$var" "$value"
      return 0
    fi

    confirm "Try pasting it again?" || {
      SKIPPED+=("$var (did not verify; re-run this script to try again)")
      return 1
    }
  done
}

banner "Is This a Scam? — setup"

# ── Stage 1  ──────────────────────────────────────────────────
stage "Claude — the half that reads the story"

say "This key turns on the Narrative Check: the half that catches scams with no"
say "link and no dodgy address in them at all. The one that starts"
say "\"Hi Mum, this is my new number, my old phone broke\"."
printf '\n'
note "Optional. Without it the app still gives a complete verdict from the"
note "deterministic rules — it just cannot see that particular scam."
printf '\n'

if confirm "Set up a Claude API key now?"; then
  open_url "https://console.anthropic.com/settings/keys"
  step "Sign in, or create an account."
  step "Click Create Key and give it a name such as is-this-a-scam."
  step "Copy the key — it is shown once and never again."
  printf '\n'
  note "Your paste is hidden, and checking it costs nothing."
  capture_key ANTHROPIC_API_KEY "Paste the Claude API key:" verify_anthropic || true
else
  SKIPPED+=("ANTHROPIC_API_KEY (declined; re-run this script to add it)")
  note "skipping — the Narrative Check stays off"
  pause
fi

# ── Stage 2  ──────────────────────────────────────────────────
stage "Google Safe Browsing — the half that checks the links"

say "This key lets the app follow shortened links to where they really go, and"
say "ask Google whether an address is on its published list of dangerous sites."
printf '\n'
note "Optional, and free for non-commercial use. Two things must happen in the"
note "Google console, and the second is the one people forget: create the key,"
note "AND switch the API on for it."
printf '\n'

if confirm "Set up a Safe Browsing key now?"; then
  open_url "https://console.cloud.google.com/apis/library/safebrowsing.googleapis.com"
  step "Sign in. If it asks, create a project — any name will do."
  step "On the page that opens, click Enable, and wait for it to finish."
  pause "Done that? Press Enter and I will open the credentials page."

  open_url "https://console.cloud.google.com/apis/credentials"
  step "Click + Create credentials at the top, then API key."
  step "Copy the key it shows you, then click Close."
  printf '\n'
  note "If you choose to restrict the key, allow the Safe Browsing API."
  capture_key SAFE_BROWSING_API_KEY "Paste the Safe Browsing key:" verify_safe_browsing || true
else
  SKIPPED+=("SAFE_BROWSING_API_KEY (declined; re-run this script to add it)")
  note "skipping — link lookups stay off"
  pause
fi

# ── Stage 3  ──────────────────────────────────────────────────
stage "Check it still passes, then run it"

say "Running the whole test suite and the type checker."
printf '\n'

if npm run verify; then
  printf '\n  %s✓ tests and types both pass%s\n' "$GREEN" "$RESET"
else
  printf '\n'
  warn "something above failed — your keys are saved, but fix this before deploying"
fi

printf '\n'
say "What is switched on:"
if [[ -n "$(_existing ANTHROPIC_API_KEY || true)" ]]; then
  printf '  %s✓%s Narrative Check — scams with no link in them\n' "$GREEN" "$RESET"
else
  printf '  %s·%s Narrative Check — off\n' "$DIM" "$RESET"
fi
if [[ -n "$(_existing SAFE_BROWSING_API_KEY || true)" ]]; then
  printf '  %s✓%s Link lookups — shortened links and the danger list\n' "$GREEN" "$RESET"
else
  printf '  %s·%s Link lookups — off\n' "$DIM" "$RESET"
fi
printf '  %s✓%s The deterministic rules — always on, no key needed\n' "$GREEN" "$RESET"
printf '\n'

# The summary prints before anything long-running starts. Ending the wizard by
# holding the dev server in the foreground meant this never ran until the server
# was stopped — and if the shell went away, it never ran at all.
finish

say "Start it whenever you like, from a terminal window you keep open:"
say ""
printf '      %snpm run dev%s   then open %shttp://localhost:3000%s\n\n' \
  "$BOLD" "$RESET" "$BOLD" "$RESET"

note "Keep that window open — the server stops when it closes. Launching it from"
note "inside another tool that then exits will stop it too, and so will Ctrl-C."
say ""
note "If the terminal says Ready but the browser cannot connect:"
note "  · allow Node.js if Windows Firewall asks"
note "  · or open http://[::1]:3000 instead, which goes over IPv6"
say ""

if confirm "Start it here now instead?"; then
  warn "this window must stay open — Ctrl-C stops the server"
  note "try pasting: ASB: unusual login. Verify at asb-secure.top"
  say ""
  npm run dev
fi
