#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — get an AI Gateway credential that works, then run the Jev spike.
#
# Why this exists: the OIDC route authenticates (GET /v1/models returns 200)
# but inference is refused with `customer_verification_required`. An AI Gateway
# API key is the credential that does not expire in hours and does not depend
# on when the token was minted. bench/jev.ts already prefers it.
#
# See docs/jev-spike.md for what the spike measures and what it costs.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
ENV_FILE=".env.local"

banner "AI Gateway key — for the Jev spike"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Confirm the card is on the team that owns this project"
say "The 403 names billing, so this is the first thing to rule out."
note "This project is linked to the team 'newtonsythong', which owns is-this-a-scam."
note "A card on a personal account rather than that team would not count."
open_url "https://vercel.com/newtonsythong/~/ai?modal=add-credit-card"
step "Check a payment method is listed for THIS team."
step "If the page shows no card, add one now — it unlocks the free credits."
pause "Press Enter once you can see a card on file."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create an AI Gateway API key"
say "Capped at \$1 and expiring in 30 days, because this spike costs under a cent"
say "and a key with no ceiling is a key nobody remembers deleting."
note "Running: vercel ai-gateway api-keys create --name jev-spike --budget 1 --expiration 30d"
printf '\n'
if npx vercel ai-gateway api-keys create --name jev-spike --budget 1 --expiration 30d; then
  printf '\n'
  step "Copy the key from the output above — it is shown once."
else
  printf '\n'
  warn "The CLI did not complete. Use the dashboard instead:"
  open_url "https://vercel.com/newtonsythong/~/ai"
  step "Open the API Keys section on that page and create a key, then copy it."
fi
ask_secret AI_GATEWAY_API_KEY "Paste the key:"
if [[ -z "${AI_GATEWAY_API_KEY:-}" ]]; then
  warn "No key entered. Re-run this wizard once you have one."
  exit 1
fi
write_env AI_GATEWAY_API_KEY "$AI_GATEWAY_API_KEY"
note "$ENV_FILE is gitignored, so the key stays out of the repository."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Prove the credential actually works"
say "One real evaluation call against Jev. Costs about one thousandth of a cent."
printf '\n'
if node -e '
process.loadEnvFile(".env.local");
fetch("https://ai-gateway.vercel.sh/v1/evaluate", {
  method: "POST",
  headers: { Authorization: "Bearer " + process.env.AI_GATEWAY_API_KEY, "Content-Type": "application/json" },
  body: JSON.stringify({
    model: "typesafe-ai/jev",
    state: "Hi Mum, this is my new number, my old phone broke. Can you send money urgently?",
    questions: { newNumber: { type: "boolean", instructions: "The sender claims to be writing from a new or borrowed number." } },
  }),
}).then(async (r) => {
  const body = await r.text();
  if (!r.ok) { console.error("  HTTP " + r.status + ": " + body.slice(0, 300)); process.exit(1); }
  const j = JSON.parse(body);
  console.log("  Jev says new-number-pretext: " + j.answers.newNumber.probability);
  console.log("  Cost: $" + (j.providerMetadata?.gateway?.cost ?? "?"));
});
'; then
  printf '\n'
  say "That is the credential working end to end, not a mocked check."
else
  printf '\n'
  warn "Still refused. Two things left to try, in order:"
  note "  1. The card may not have propagated yet — wait a few minutes and re-run."
  note "  2. Confirm the card is on the 'newtonsythong' TEAM, not the personal account."
  exit 1
fi
pause "Press Enter to continue."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Run stage one of the spike"
say "146 messages, the dev half only, about \$0.006."
say "The run prints what it will cost before it spends, caches every answer,"
say "and sweeps every threshold for free afterwards."
note "The test half is refused by the runner — it is the only instrument left."
printf '\n'
if confirm "Run npm run bench:jev now?"; then
  printf '\n'
  npm run bench:jev
else
  note "Skipped. Run it yourself any time with: npm run bench:jev"
fi

finish
